# Generated by Django 6.0.2 on 2026-04-11 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_news_options_alter_product_options_news_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='video',
            field=models.FileField(blank=True, help_text='Поддерживаемые форматы: MP4, WebM', null=True, upload_to='news/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm'])], verbose_name='Видео'),
        ),
    ]
