# Generated by Django 6.0.2 on 2026-04-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_news_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('vk', models.URLField(blank=True, verbose_name='ВКонтакте')),
                ('address', models.TextField(blank=True, verbose_name='Адрес торговли')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Избранная новость'),
        ),
        migrations.AddField(
            model_name='news',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
