# Generated by Django 6.0.2 on 2026-04-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contactinformation_news_is_featured_news_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['is_featured'], name='main_news_is_feat_8a3783_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['published'], name='main_news_publish_2192c9_idx'),
        ),
    ]
