# Generated by Django 6.0.2 on 2026-04-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_news_options_alter_news_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinformation',
            name='info',
            field=models.TextField(blank=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='messenger_max',
            field=models.URLField(blank=True, verbose_name='Мессенджер MAX'),
        ),
    ]
