# Generated by Django 6.0.2 on 2026-04-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_contactinformation_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinformation',
            name='yandex_widget',
            field=models.TextField(blank=True, null=True, verbose_name='Яндекс карты'),
        ),
    ]
