# Generated by Django 6.0.2 on 2026-05-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Закреплена'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['is_pinned'], name='main_news_is_pinn_a67c93_idx'),
        ),
    ]
